# apiVersion: gateway.networking.k8s.io/v1alpha2
# kind: UDPRoute
# metadata:
#   name: wg-guardian-51820
# spec:
#   parentRefs:
#   - group: gateway.networking.k8s.io
#     kind: Gateway
#     name: istio-dev
#     namespace: istio-system
#     sectionName: udp-wg-51820
#   rules:
#   - backendRefs:
#     - name: wg-guardian
#       port: 51820
# ---
#kubectl patch gateway eg --type=json --patch '
#  - op: add
#    path: /spec/listeners/-
#    value:
#      name: coredns
#      protocol: UDP
#      port: 5300
#      allowedRoutes:
#        kinds:
#        - kind: UDPRoute
#
