apiVersion: v1
kind: Secret
metadata:
  name: wireguard-config
  namespace: {{ .Release.Namespace }}
stringData:
  wg0.conf: |
{{- if and (hasKey .Values.wireguard "wgConf") (not (empty .Values.wireguard.wgConf)) }}
{{ .Values.wireguard.wgConf | indent 4 }}
{{- else }}
    [Interface]
    PrivateKey = MAcKuLFHLDnwRddk54TCOZgBZtQ+liDYgA4ARUtktnA=
    ListenPort = 51820
    Address = 10.0.0.1/24
    DNS = 10.0.0.1, 10.43.0.10, 1.1.1.1, 8.8.8.8, 9.9.9.9
    MTU = 1420

    [Peer]
    PublicKey = 52KSeddkDYrCdYGdKuV6y3Q6Zv6geFpvwv3xvLuWQ24=
    AllowedIPs = 10.0.0.2/32
    # Endpoint = 0.0.0.0:51820 # peer's public IP
    PersistentKeepalive = 25
    
    [Peer]
    PublicKey = qSdIrnWCNwa0pYVFfSNGe1clzl0qXEM15ZEQBt3PWTw=
    AllowedIPs = 10.0.0.3/32
    # Endpoint = 0.0.0.0:51820 # peer's public IP
    PersistentKeepalive = 25
{{- end }}
---
