apiVersion: v1
kind: Secret
metadata:
  name: explorer-connection-profile
  namespace: {{ .Values.org }}
stringData:
  connection-profile.json: |
    {
      "name": "test-network",
      "version": "1.0.0",
      "client": {
        "tlsEnable": true,
        "adminCredential": {
          "id": "{{ .Values.admin.id }}",
          "password": "{{ .Values.admin.password }}"
        },
        "enableAuthentication": true,
        "organization": "{{ include "capitalizeFirst" .Values.org }}MSP",
        "connection": {
          "timeout": {
            "peer": {
              "endorser": "300"
            },
            "orderer": "300"
          }
        }
      },
      "channels": {
        "default": {
          "peers": {
            "peer0.{{ .Values.org }}": {}
          }
        }
      },
      "organizations": {
        "{{ include "capitalizeFirst" .Values.org }}MSP": {
          "mspid": "{{ include "capitalizeFirst" .Values.org }}MSP",
          "fullpath": true,
          "adminPrivateKey": {
            "path": "/fabric/{{ .Values.org }}/admin/msp/keystore/key.pem"
          },
          "peers": [
            "peer0.{{ .Values.org }}"
          ],
          "signedCert": {
            "path": "/fabric/{{ .Values.org }}/admin/msp/signcerts/cert.pem"
          }
        }
      },
      "peers": {
        "peer0.{{ .Values.org }}": {
          "tlsCACerts": {
            "path": "/fabric/{{ .Values.org }}/tls/tlscacert.pem"
          },
          "url": "grpcs://peer0.{{ .Values.org }}:7051"
        }
      }
    }
---