{{- range .Values.orgs }}
{{ if $.Values.cc.image }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ $.Values.cc.name }}
  name: {{ $.Values.cc.name }}
  namespace: {{ .name }}
spec:
  replicas: {{ $.Values.cc.replicas | default (len .peers) }}
  selector:
    matchLabels:
      app: {{ $.Values.cc.name }}
  template:
    metadata:
      labels:
        app: {{ $.Values.cc.name }}
    spec:
      {{- if $.Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml $.Values.imagePullSecrets | nindent 6 }}
      {{- end }}
      securityContext:
        {{- toYaml $.Values.securityContext | nindent 8 }}
      containers:
      - image: {{ $.Values.cc.image }}
        imagePullPolicy: Always
        name: {{ $.Values.cc.name }}
        ports:
        - containerPort: 7052
        env:
        - name: CHAINCODE_ID
          valueFrom:
            configMapKeyRef:
              name: {{ $.Values.cc.name }}-package-id
              key: package-id
        - name: CHAINCODE_TLS_CLIENT_CACERT
          value: ""
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ $.Values.cc.name }}
  name: {{ $.Values.cc.name }}
  namespace: {{ .name }}
spec:
  ports:
  - name: grpc
    port: 7052
    protocol: TCP
    targetPort: 7052
  selector:
    app: {{ $.Values.cc.name }}
  type: ClusterIP
---
{{- end }}
{{- end }}
