apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: fabric-peer
    app.kubernetes.io/instance: {{ .Release.Name }}
  name: {{ .Values.peer.name }}
  namespace: {{ .Values.peer.org }}
spec:
  ports:
  - name: grpc
    port: 7051
    protocol: TCP
    targetPort: 7051
  # - name: http-admin
  #   port: 9443
  #   protocol: TCP
  #   targetPort: 9443
  # - name: http-operations
  #   port: 8443
  #   protocol: TCP
  #   targetPort: 8443
  selector:
    app.kubernetes.io/name: fabric-peer
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: ClusterIP
---