{{- if .Values.tlsRoute.enabled }}
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: {{ .Values.peer.name }}.{{ .Values.peer.org }}
  namespace: {{ .Values.peer.org }}
spec:
  hostnames:
  - {{ .Values.peer.name }}.{{ .Values.peer.org }}.{{ .Values.network.publicDomain }}
  - {{ .Values.peer.name }}-{{ .Values.peer.org }}.{{ .Values.network.publicDomain }}
  parentRefs:
  {{- toYaml .Values.tlsRoute.parentRefs | nindent 2 }}
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: {{ .Values.peer.name }}
      port: 7051
      weight: 1
{{- end }}
---
