{{- if not .Values.cluster.existingEtcSecretName }}
{{- $secretName := printf "%s-etc" (include "couchdb.fullname" .) }}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $secretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "couchdb.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if $existingSecret }}
  COUCHDB_ERLANG_COOKIE: {{ index $existingSecret.data "COUCHDB_ERLANG_COOKIE" | b64dec }}
  {{- else }}
  COUCHDB_ERLANG_COOKIE: {{ .Values.cluster.erlangCookie | default (randAlphaNum 32) }}
  {{- end }}
  {{- if $existingSecret }}
  COUCHDB_SECRET: {{ index $existingSecret.data "COUCHDB_SECRET" | b64dec }}
  {{- else }}
  COUCHDB_SECRET: {{ .Values.cluster.secret | default (randAlphaNum 32) }}
  {{- end }}
  kubernetes.ini: |
    [chttpd]
    bind_address = any
    
    [couchdb]
    {{- if $existingSecret }}
    {{- $kubernetesIni := index $existingSecret.data "kubernetes.ini" | b64dec }}
    {{- $uuidLine := regexFind "uuid = [a-f0-9-]+" $kubernetesIni }}
    {{- if $uuidLine }}
    {{ $uuidLine }}
    {{- else }}
    uuid = {{ .Values.cluster.uuid | default (uuidv4) }}
    {{- end }}
    {{- else }}
    uuid = {{ .Values.cluster.uuid | default (uuidv4) }}
    {{- end }}
---
{{- end }}
