{{- if not .Values.admin.existingSecretName }}
{{- $secretName := printf "%s-admin" (include "couchdb.fullname" .) }}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $secretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "couchdb.labels" . | nindent 4 }}
type: Opaque
stringData:
  COUCHDB_USER: {{ .Values.admin.user | default "admin" }}
  {{- if $existingSecret }}
  COUCHDB_PASSWORD: {{ index $existingSecret.data "COUCHDB_PASSWORD" | b64dec }}
  {{- else }}
  COUCHDB_PASSWORD: {{ .Values.admin.password | default (randAlphaNum 32) }}
  {{- end }}
---
{{- end }}
