apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "couchdb.labels" . | nindent 4 }}
  name: {{ include "couchdb.fullname" . }}
spec:
  ports:
  - name: http-couchdb
    port: 5984
    protocol: TCP
    targetPort: http-couchdb
  selector:
    {{- include "couchdb.selectorLabels" . | nindent 4 }}
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "couchdb.labels" . | nindent 4 }}
  name: {{ include "couchdb.fullname" . }}-hl
spec:
  clusterIP: None
  ports:
  - name: http-couchdb
    port: 5984
    protocol: TCP
    targetPort: http-couchdb
  - name: tcp-epmd
    port: 4369
    protocol: TCP
    targetPort: tcp-epmd
  - name: tcp-cluster
    port: 9100
    protocol: TCP
    targetPort: tcp-cluster
  publishNotReadyAddresses: true
  selector:
    {{- include "couchdb.selectorLabels" . | nindent 4 }}
  type: ClusterIP
---
