apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: fabric-ca
    app.kubernetes.io/instance: {{ .Release.Name }}
  name: ca
  namespace: {{ .Values.caOrg }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: fabric-ca
      app.kubernetes.io/instance: {{ .Release.Name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fabric-ca
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - command:
        - sh
        - -c
        - |
          fabric-ca-server start -d -b ${CA_ADMIN}:${CA_ADMIN_PASSWORD}
        ports:
        - containerPort: 7054
          name: ca
        - containerPort: 9443
          name: operation
        envFrom:
        - configMapRef:
            name: ca-config
        env:
        - name: CA_ADMIN
          valueFrom:
            secretKeyRef:
              name: ca-admin-login
              key: username
        - name: CA_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ca-admin-login
              key: password
        image: {{ .Values.image.repository | default "docker.io/hyperledger/fabric-ca" }}:{{ .Values.image.tag | default "latest" }}
        imagePullPolicy: Always
        name: fabric-ca
        volumeMounts:
        - mountPath: /etc/hyperledger/fabric-ca-server/ca-certs
          name: ca-keypair
        - mountPath: /etc/hyperledger/fabric-ca-server/tlsca-certs
          name: tlsca-keypair
        - mountPath: /etc/hyperledger/fabric-ca-server
          name: data
      securityContext:
        {{- toYaml $.Values.securityContext | nindent 8 }}
      volumes:
      - name: data
        {{- if eq .Values.pvc.enabled true }}
        persistentVolumeClaim:
          claimName: ca-data
        {{- else }}
        emptyDir: {}
        {{- end }}
      - name: tlsca-keypair
        secret:
          secretName: tlsca.{{ .Values.caOrg }}-keypair
      - name: ca-keypair
        secret:
          secretName: ca.{{ .Values.caOrg }}-keypair
---
