apiVersion: v1
data:
  password: YWRtaW5wdw==
  username: YWRtaW4=
kind: Secret
metadata:
  name: ca-admin-login
  namespace: {{ .Values.caOrg }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
type: kubernetes.io/basic-auth
---
