apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.caOrg }}-tlscacerts-admincerts-distributor
  namespace: {{ .Values.caOrg }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.caOrg }}-tlscacerts-admincerts-distributor
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.caOrg }}-tlscacerts-admincerts-distributor
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.caOrg }}-tlscacerts-admincerts-distributor
subjects:
- kind: ServiceAccount
  name: {{ .Values.caOrg }}-tlscacerts-admincerts-distributor
  namespace: {{ .Values.caOrg }}
---