{{- if .Values.tlsRoute.enabled }}
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: ca.{{ .Values.caOrg }}
  namespace: {{ .Values.caOrg }}
spec:
  hostnames:
  - ca.{{ .Values.caOrg }}.{{ .Values.network.publicDomain }}
  - ca-{{ .Values.caOrg }}.{{ .Values.network.publicDomain }}
  parentRefs:
  {{- toYaml .Values.tlsRoute.parentRefs | nindent 2 }}
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: ca
      port: 7054
      weight: 1
{{- end }}
---
