apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.orderer.name }}-config
  namespace: orderer
  labels:
    app.kubernetes.io/name: fabric-orderer
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  config.yaml: |-
    NodeOUs:
      Enable: true
      ClientOUIdentifier:
        Certificate: cacerts/cacert.pem
        OrganizationalUnitIdentifier: client
      PeerOUIdentifier:
        Certificate: cacerts/cacert.pem
        OrganizationalUnitIdentifier: peer
      AdminOUIdentifier:
        Certificate: cacerts/cacert.pem
        OrganizationalUnitIdentifier: admin
      OrdererOUIdentifier:
        Certificate: cacerts/cacert.pem
        OrganizationalUnitIdentifier: orderer
---