{{- if .Values.tlsRoute.enabled }}
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: {{ .Values.orderer.name }}.orderer
  namespace: orderer
spec:
  hostnames:
  - {{ .Values.orderer.name }}.orderer.{{ .Values.network.publicDomain }}
  - {{ .Values.orderer.name }}-orderer.{{ .Values.network.publicDomain }}
  parentRefs:
  {{- toYaml .Values.tlsRoute.parentRefs | nindent 2 }}
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: {{ .Values.orderer.name }}
      port: 7050
      weight: 1
{{- end }}
---
