apiVersion: v2
name: fabric-peer
description: Fabric Peer stores and manages copies of ledgers and smart contracts aka chaincode
type: application
version: 0.0.1
appVersion: 2.5.4
icon: https://imagedelivery.net/JANQz1aoc0j0z4-hBEPBbg/4bf349ce-1dd0-4e80-d8e9-34cf8e151300/public
keywords: ["hyperledger", "fabric", "fabric-peer"]
annotations:
  category: Blockchain
maintainers:
- name: edgeflare.io
  email: dev@edgeflare.io
  url: https://github.com/edgeflare/charts
dependencies:
- name: couchdb
  version: "4.5.6"
  repository: "https://apache.github.io/couchdb-helm"
  condition: couchdb.enabled
  tags:
  - fabric-peer-state-database